name: Terraform Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6       - name: Init Terraform
      working-directory: iac/terraform/envs/dev
      run: terraform init -backend=false

    - name: Validate Terraform
      working-directory: iac/terraform/envs/dev
      run: terraform validate
